name: Scrape and Commit Feed

on:
  schedule:
    - cron: '0 9 * * *'  # UTC(09:00) -> Italia: ora standard (CET = UTC+1): 09:00 UTC è 10:00 CET; ora legale (CEST, UTC+2): 09:00 UTC è 11:00 CEST
    - cron: '0 11 * * *' # UTC(11:00) -> Italia: ora standard (CET = UTC+1): 11:00 UTC è 12:00 CET; ora legale (CEST, UTC+2): 11:00 UTC è 13:00 CEST
    - cron: '0 13 * * *' # UTC(13:00) -> Italia: ora standard (CET = UTC+1): 13:00 UTC è 14:00 CET; ora legale (CEST, UTC+2): 13:00 UTC è 15:00 CEST
    - cron: '0 15 * * *' # UTC(15:00) -> Italia: ora standard (CET = UTC+1): 15:00 UTC è 16:00 CET; ora legale (CEST, UTC+2): 15:00 UTC è 17:00 CEST
    - cron: '0 17 * * *' # UTC(17:00) -> Italia: ora standard (CET = UTC+1): 17:00 UTC è 18:00 CET; ora legale (CEST, UTC+2): 17:00 UTC è 19:00 CEST
    
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run scraping script
        run: |
          python3 alboPretorioFeed_v2.py
          
      - name: Check for changes
        id: check_diff
        run: |
          if git diff --exit-code --quiet feed.xml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"
          git add feed.xml
          git commit -m "Aggiornamento feed.xml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

